services:
  database:
    image: postgres
    restart: always
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: password
    networks:
      - be-db-network

  backend:
    depends_on:
      - database
    build:
      context: ./example-nestjs
    container_name: example-nestjs-backend
    env_file:
      - ./example-nestjs/.env
    ports:
      - '1337:1337'
    volumes:
      - ./example-nestjs/src:/usr/src/app/src
    command: npm run start:dev
    networks:
      - be-db-network
      - be-fe-network

  frontend:
    build:
      context: ./example-nextjs
    container_name: example-nextjs-frontend
    env_file:
      - ./example-nextjs/.env
    ports:
      - '3000:3000'
    volumes:
      - ./example-nextjs/src:/usr/src/app/src
    command: npm run dev
    networks:
      - be-fe-network

networks:
  be-db-network:
    driver: bridge
  be-fe-network:
    driver: bridge
